var questions={
	"Hi":"Hi I am Your assistant,Tell What you want",
  "hi":"Hi I am Your assistant,Tell What you want",

	"Whats your name":"I am simply airbus assistant",
	"Name":"I am simply airbus assistant",
	"What are the products available":"We provide aircraft and Helicopters",
	"What products are available":"We provide aircraft and Helicopters",
	"What types of aircraft are available":"currently, passenger aircraft, corporate jets, Previous-generation aircraft and fighter aircraft are available",
	"What types of aircraft you provide":"currently, passenger aircraft, corporate jets, Previous-generation aircraft and fighter aircraft are available",
	"What types of aircraft":"currently, passenger aircraft, corporate jets, Previous-generation aircraft and fighter aircraft are available",
	"What models of passenger aircraft are available":"we provide A220 A320 A330 A350 and A380 passenger aircraft models",
	"What models of passenger aircraft you provide":"we provide A220 A320 A330 A350 and A380 passenger aircraft models",
	"What models of passenger aircraft":"we provide A220 A320 A330 A350 and A380 passenger aircraft models",
	"Passenger aircraft":"we provide A220 A320 A330 A350 and A380 passenger aircraft models",
	"What models of corporate jets are available":"we provide ACJ22, ACJ319neo, ACJ320neo, ACJ330neo, and ACJ350 XWB",
	"What models of corporate jets you provide":"we provide ACJ22, ACJ319neo, ACJ320neo, ACJ330neo, and ACJ350 XWB",
	"What models of corporate jets":"we provide ACJ22, ACJ319neo, ACJ320neo, ACJ330neo, and ACJ350 XWB",
	"Corporate jets":"we provide ACJ22, ACJ319neo, ACJ320neo, ACJ330neo, and ACJ350 XWB",
	"What models of fighter aircraft are available":"we provide A330-200F, A330P2F, BelugaST, and BeluguXL",
	"What models of fighter aircraft you provide":"we provide A330-200F, A330P2F, BelugaST, and BeluguXL",
	"What models of fighter aircraft":"we provide A330-200F, A330P2F, BelugaST, and BeluguXL",
	"Fighter aircraft":"we provide A330-200F, A330P2F, BelugaST, and BeluguXL",
	"What models of Previous-generation aircraft are available":"we provide A300-600, A300-600F, A310, and A340 Family",
	"What models of Previous-generation aircraft you provide":"we provide A300-600, A300-600F, A310, and A340 Family",
	"What models of Previous-generation aircraft":"we provide A300-600, A300-600F, A310, and A340 Family",
	"Previous-generation aircraft":"we provide A300-600, A300-600F, A310, and A340 Family",

	"whats your name":"I am simply airbus assistant",
	"name":"I am simply airbus assistant",
	"what are the products available":"We provide aircraft and Helicopters",
	"what products are available":"We provide aircraft and Helicopters",
	"what types of aircraft are available":"currently, passenger aircraft, corporate jets, Previous-generation aircraft and fighter aircraft are available",
	"what types of aircraft you provide":"currently, passenger aircraft, corporate jets, Previous-generation aircraft and fighter aircraft are available",
	"what types of aircraft":"currently, passenger aircraft, corporate jets, Previous-generation aircraft and fighter aircraft are available",
	"what models of passenger aircraft are available":"we provide A220 A320 A330 A350 and A380 passenger aircraft models",
	"what models of passenger aircraft you provide":"we provide A220 A320 A330 A350 and A380 passenger aircraft models",
	"what models of passenger aircraft":"we provide A220 A320 A330 A350 and A380 passenger aircraft models",
	"passenger aircraft":"we provide A220 A320 A330 A350 and A380 passenger aircraft models",
	"what models of corporate jets are available":"we provide ACJ22, ACJ319neo, ACJ320neo, ACJ330neo, and ACJ350 XWB",
	"what models of corporate jets you provide":"we provide ACJ22, ACJ319neo, ACJ320neo, ACJ330neo, and ACJ350 XWB",
	"what models of corporate jets":"we provide ACJ22, ACJ319neo, ACJ320neo, ACJ330neo, and ACJ350 XWB",
	"corporate jets":"we provide ACJ22, ACJ319neo, ACJ320neo, ACJ330neo, and ACJ350 XWB",
	"what models of fighter aircraft are available":"we provide A330-200F, A330P2F, BelugaST, and BeluguXL",
	"what models of fighter aircraft you provide":"we provide A330-200F, A330P2F, BelugaST, and BeluguXL",
	"what models of fighter aircraft":"we provide A330-200F, A330P2F, BelugaST, and BeluguXL",
	"fighter aircraft":"we provide A330-200F, A330P2F, BelugaST, and BeluguXL",
	"what models of Previous-generation aircraft are available":"we provide A300-600, A300-600F, A310, and A340 Family",
	"what models of Previous-generation aircraft you provide":"we provide A300-600, A300-600F, A310, and A340 Family",
	"what models of Previous-generation aircraft":"we provide A300-600, A300-600F, A310, and A340 Family",
	"previous-generation aircraft":"we provide A300-600, A300-600F, A310, and A340 Family",


	
	

	"Can you tell me about A220 Family passenger aircrafts":"These aircraft expand the Airbus single-aisle family to cover the 100-150 seat segment – and respond to a worldwide market demand for smaller single-aisle jetliners.",
	"Can you tell me about A320 Family passenger aircrafts":"The A320 is one aircraft in four sizes (A318, A319, A320 and A321), representing the most successful and versatile jetliner family ever. Seating from 100 to 240 passengers and flying throughout the world, with the widest single-aisle cabin, an A320 takes off or lands every 1.6 seconds.",
	"Can you tell me about A330 Family passenger aircrafts":"The A330neo is a true example of a highly-innovative aircraft that delivers superior quality and efficiency, The A330neo is powered by high-bypass ratio, new generation engines and designed with an advanced high-span wing vastly improving the aerodynamics.",
	"Can you tell me about A350 Family passenger aircrafts":"Family aircraft.",
	"Can you tell me about A380 Family passenger aircrafts":"It has two full-length decks with wide-body dimensions, meaning its two passenger levels offer an entire deck’s worth of additional space compared to the next largest twin-engine jetliner.",
	"Can you tell me about ACJ319neo corporate jets":"the ACJ319neo delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"Can you tell me about ACJ22 corporate jets":"the ACJ22 delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"Can you tell me about ACJ330neo corporate jets":"the ACJ330neo delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"Can you tell me about ACJ350 XWB corporate jets":"the ACJ350 XWD delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"Can you tell me about A330-200F fighter aircraft":"The A330-200F features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",
	"Can you tell me about A330P2F fighter aircraft":"The A330P2F features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",
	"Can you tell me about BelugaST fighter aircraft":"The BelugaST features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",
	"Can you tell me about BeluguXL fighter aircraft":"The BeluguXL features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",

	"A220 Family passenger aircrafts":"These aircraft expand the Airbus single-aisle family to cover the 100-150 seat segment – and respond to a worldwide market demand for smaller single-aisle jetliners.",
	"A320 Family passenger aircrafts":"The A320 is one aircraft in four sizes (A318, A319, A320 and A321), representing the most successful and versatile jetliner family ever. Seating from 100 to 240 passengers and flying throughout the world, with the widest single-aisle cabin, an A320 takes off or lands every 1.6 seconds.",
	"A330 Family passenger aircrafts":"The A330neo is a true example of a highly-innovative aircraft that delivers superior quality and efficiency, The A330neo is powered by high-bypass ratio, new generation engines and designed with an advanced high-span wing vastly improving the aerodynamics.",
	"A350 Family passenger aircrafts":"Family aircraft.",
	"A380 Family passenger aircrafts":"It has two full-length decks with wide-body dimensions, meaning its two passenger levels offer an entire deck’s worth of additional space compared to the next largest twin-engine jetliner.",
	"ACJ319neo corporate jets":"the ACJ319neo delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"ACJ22 corporate jets":"the ACJ22 delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"ACJ330neo corporate jets":"the ACJ330neo delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"ACJ350 XWB corporate jets":"the ACJ350 XWD delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"A330-200F fighter aircraft":"The A330-200F features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",
	"A330P2F fighter aircraft":"The A330P2F features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",
	"BelugaST fighter aircraft":"The BelugaST features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",
	"BeluguXL fighter aircraft":"The BeluguXL features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",

	"A220":"These aircraft expand the Airbus single-aisle family to cover the 100-150 seat segment – and respond to a worldwide market demand for smaller single-aisle jetliners.",
	"A320":"The A320 is one aircraft in four sizes (A318, A319, A320 and A321), representing the most successful and versatile jetliner family ever. Seating from 100 to 240 passengers and flying throughout the world, with the widest single-aisle cabin, an A320 takes off or lands every 1.6 seconds.",
	"A330":"The A330neo is a true example of a highly-innovative aircraft that delivers superior quality and efficiency, The A330neo is powered by high-bypass ratio, new generation engines and designed with an advanced high-span wing vastly improving the aerodynamics.",
	"A350":"Family aircraft.",
	"A380":"It has two full-length decks with wide-body dimensions, meaning its two passenger levels offer an entire deck’s worth of additional space compared to the next largest twin-engine jetliner.",
	"ACJ319neo":"the ACJ319neo delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"ACJ22":"the ACJ22 delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"ACJ330neo":"the ACJ330neo delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"ACJ350 XWB":"the ACJ350 XWD delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"A330-200F":"The A330-200F features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",
	"A330P2F":"The A330P2F features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",
	"BelugaST":"The BelugaST features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",
	"BeluguXL":"The BeluguXL features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",

	
	"can you tell me about A220 Family passenger aircrafts":"These aircraft expand the Airbus single-aisle family to cover the 100-150 seat segment – and respond to a worldwide market demand for smaller single-aisle jetliners.",
	"can you tell me about A320 Family passenger aircrafts":"The A320 is one aircraft in four sizes (A318, A319, A320 and A321), representing the most successful and versatile jetliner family ever. Seating from 100 to 240 passengers and flying throughout the world, with the widest single-aisle cabin, an A320 takes off or lands every 1.6 seconds.",
	"can you tell me about A330 Family passenger aircrafts":"The A330neo is a true example of a highly-innovative aircraft that delivers superior quality and efficiency, The A330neo is powered by high-bypass ratio, new generation engines and designed with an advanced high-span wing vastly improving the aerodynamics.",
	"can you tell me about A350 Family passenger aircrafts":"Family aircraft.",
	"can you tell me about A380 Family passenger aircrafts":"It has two full-length decks with wide-body dimensions, meaning its two passenger levels offer an entire deck’s worth of additional space compared to the next largest twin-engine jetliner.",
	"can you tell me about ACJ319neo corporate jets":"the ACJ319neo delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"can you tell me about ACJ22 corporate jets":"the ACJ22 delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"can you tell me about ACJ330neo corporate jets":"the ACJ330neo delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"can you tell me about ACJ350 XWB corporate jets":"the ACJ350 XWD delivers better range and better comfort. In addition, it offers a lower cabin altitude, equivalent to an average of less than 6,400 ft – delivering an atmosphere that is even closer to that experienced on the ground for enhanced passenger comfort.",
	"can you tell me about A330-200F fighter aircraft":"The A330-200F features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",
	"can you tell me about A330P2F fighter aircraft":"The A330P2F features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",
	"can you tell me about BelugaST fighter aircraft":"The BelugaST features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",
	"can you tell me about BeluguXL fighter aircraft":"The BeluguXL features an optimised fuselage cross-section, offering flexibility to carry a wide variety of pallet and container sizes. The aircraft offers 30% more volume than any freighter in its class, and is based on the proven and technologically-advanced A330 platform, for which Airbus has over 1,000 orders and already more than 650 aircraft in service.",

	"tell me about aircraft":"An aircraft is a vehicle that is able to fly by gaining support from the air. It counters the force of gravity by using either static lift or by using the dynamic lift of an airfoil, or in a few cases the downward thrust from jet engines.",
	"tell me about airline":"An airline is a company that provides air transport services for traveling passengers and freight. Airlines utilize aircraft to supply these services and may form partnerships or alliances with other airlines for codeshare agreements, in which they both offer and operate the same flight.",
	"tell me about airbus":"Airbus SE is a European multinational aerospace corporation. As of 2019, Airbus is the world's largest airliner manufacturer and took the most airliner orders, surpassing rival Boeing",
	"Tell me about aircraft":"An aircraft is a vehicle that is able to fly by gaining support from the air. It counters the force of gravity by using either static lift or by using the dynamic lift of an airfoil, or in a few cases the downward thrust from jet engines.",
	"Tell me about airline":"An airline is a company that provides air transport services for traveling passengers and freight. Airlines utilize aircraft to supply these services and may form partnerships or alliances with other airlines for codeshare agreements, in which they both offer and operate the same flight.",
	"Tell me about airbus":"Airbus SE is a European multinational aerospace corporation. As of 2019, Airbus is the world's largest airliner manufacturer and took the most airliner orders, surpassing rival Boeing",

	"purchase":"thank you for purchasing at airlines",
	"bye":"Thank you for using airbus assistant",
	"Bye":"Thank you for using airbus assistant",
	"Thanks":"you are welcome",
	"thanks":"you are welcome",
	"Thank you":"you are welcome",
	"thank you":"you are welcome",




};